print("hello")
print("two hello")
print("two hello")
print("two hello")
print("two hello")
print("two hello")
print("two hello")
print("two hello")
print("two hello")
print("two hello")
print("two hello")